#!/bin/sh
slugify() {
  echo "$1" \
    | iconv -t ascii//TRANSLIT \
    | sed -E 's#refs/[^\/]*/##' \
    | sed -E 's/[^a-zA-Z0-9]+/-/g' \
    | sed -E 's/^-+|-+$//g' \
    | tr A-Z a-z
}
slugify "$*"