name: Serverless deploy

on: push

env:
  COMMIT_SHA: "${{ github.sha }}"
  GIT_REF: "${{ github.ref }}"
  LOG_LEVEL: "WARN"

  REGION: "us-east-2"
  S3_BUCKET: "www.carlosguerrero.com"
  DOMAIN: "carlosguerrero.com"

jobs:
  deploy:
    name: "Deploy Serverless"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Set extra environment variables
        run: echo "BRANCH_REF_SLUG=$(./.github/slugify "$GIT_REF")" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - uses: actions/cache@v1
        id: node-modules-cache
        with:
          key: /node_modules-${{ hashFiles('**/yarn.lock') }}
          path: /node_modules

      - name: Install node_modules
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Serverless Deploy
        run: yarn run deploy --stage "$BRANCH_REF_SLUG" --region "$REGION" --verbose
